export const ENGLISH_STRINGS = {
  appName: "DevTracker",
  documentTitle: "DevTracker Dashboard",
  skipToDashboard: "Skip to dashboard",
  dashboardViews: "Dashboard views",
  dateRange: "Date range",
  views: {
    today: "Today",
    project: "Project",
    quality: "Workflow",
    global: "Global",
  },
  ranges: {
    today: "Today",
    week: "Last Week",
    month: "Last Month",
    all: "Last 90 Days",
  },
  subtitles: {
    today: "Live view of your current coding rhythm.",
    project:
      "Range-based activity time, concentration, editor changes, languages, and active files.",
    quality:
      "Descriptive diagnostics, saves, debug time, and Git branch context.",
    global: "Your long-term work patterns across tracked projects.",
  },
  metrics: {
    activeToday: "Active Today",
    dailyGoal: "Daily Goal",
    topThreeFileShare: "Top-3 File Share",
    currentFlow: "Current Flow",
    characterEditVolume: "Character Edit Volume",
    approximateLineActivity: "Approx. Line Activity",
    currentDiagnostics: "Current Diagnostics",
    gitContext: "Git Context",
    projectTime: "Project Time",
    characterEditsPerHour: "Character Edits / Active Hour",
    removalShare: "Removal Share (Approx.)",
    errors: "Errors",
    warnings: "Warnings",
    saves: "Saves",
    debugTime: "Debug Time",
    trackedTime: "Tracked Time",
    projects: "Projects",
    mostActiveHour: "Most Active Hour",
  },
  panels: {
    todayTimeline: "Today Timeline",
    sessionLanguages: "Session Languages",
    activeFiles: "Active Files",
    activityTrend: "Activity Trend",
    languages: "Languages",
    mostActiveFiles: "Most Active Files",
    diagnosticsTrend: "Diagnostics Trend",
    branchMix: "Branch Mix",
    currentSignals: "Current Signals",
    weeklyHeatmap: "Weekly Heatmap",
    topProjects: "Top Projects",
    globalLanguages: "Global Languages",
  },
  empty: {
    noActivity: "No activity yet",
    noActiveFile: "No active file",
    noSessionLanguages: "No session languages yet",
    noActiveFilesToday: "No active files today",
    noLanguagesInRange: "No languages in this range",
    noActivityInRange: "No activity in this range",
    gitUnavailable: "Git unavailable",
    diagnosticsUnavailable: "Diagnostics unavailable",
    noGlobalLanguageActivity: "No global language activity",
  },
  dayNames: ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"],
  chartLabels: {
    hours: "Hours",
    errors: "Errors",
    warnings: "Warnings",
    info: "Info",
  },
  tableHeaders: {
    file: ["File", "Time", "Activity samples"],
    project: ["Project", "Time", "Top-3 share"],
  },
  signals: {
    errors: "Errors",
    warnings: "Warnings",
    info: "Info",
    hints: "Hints",
    dirtyFiles: "Dirty files",
  },
  phrases: {
    session: "Session",
    longest: "Longest",
    of: "of",
    editEvents: "edit events",
    largeEditEvents: "large edit events",
    inserted: "inserted",
    removedLineBreaksApprox: "removed line breaks (approx.)",
    errors: "errors",
    warnings: "warnings",
    trackedDays: "tracked days",
    observedEditorTransitions: "Observed editor transitions",
    approximateLineBreakChanges: "approximate line-break changes",
    tracked: "tracked",
    savesPerHour: "saves/hour",
  },
  initial: {
    zeroEditEvents: "0 edit events",
    approximateNetZeroLineBreaks: "Approx. net 0 line breaks",
    zeroWarnings: "0 warnings",
    zeroSavesPerHour: "0 saves/hour",
    zeroObservedEditorTransitions: "Observed editor transitions 0",
    legacyApproximation: "Legacy v1 approximation",
    zeroApproximateLineBreakChanges: "0 approximate line-break changes",
  },
  aria: {
    activeTimeToday: "Active time today",
    dailyGoalProgress: "Daily goal progress",
    topThreeFileShare: "Top three file share",
    currentFlowBlock: "Current flow block",
    characterEditVolume: "Character edit volume",
    approximateLineActivity: "Approximate line activity",
    currentDiagnostics: "Current diagnostics",
    gitContext: "Git context",
    activeHoursTodayChart: "Bar chart of active hours today",
    projectHoursChart: "Bar chart of project active hours",
    diagnosticsChart: "Stacked chart of diagnostics by severity",
  },
  status: {
    dataUnavailable: "Dashboard data is temporarily unavailable",
    currentProject: "Current Project",
    currentSnapshot: "Current snapshot",
    selectedRange: "Selected range",
    allTrackedActivity: "All tracked activity",
    withActivity: "With activity",
    targetZeroMinutes: "Target 0m",
    sessionZeroMinutes: "Session 0m",
    longestZeroMinutes: "Longest 0m",
  },
} as const;

export type EnglishStrings = typeof ENGLISH_STRINGS;
