export const ENGLISH_STRINGS = {
  appName: "DevTracker",
  documentTitle: "DevTracker Dashboard",
  skipToDashboard: "Skip to dashboard",
  dashboardViews: "Dashboard views",
  dateRange: "Date range",
  projectSelector: "Project",
  selectProject: "Select a project",
  actions: "Actions",
  actionItems: {
    export: "Export",
    settings: "Settings",
    openData: "Open Data",
    reset: "Reset",
  },
  views: {
    today: "Overview",
    project: "Trends",
    quality: "Workflow",
    global: "Projects",
  },
  ranges: {
    today: "Today",
    week: "Last Week",
    month: "Last Month",
    all: "Last 90 Days",
  },
  subtitles: {
    today: "Live view of today’s coding activity across tracked projects.",
    project:
      "Range-based activity time and patterns for the selected project.",
    quality:
      "Descriptive diagnostics, saves, debug time, and Git branch context.",
    global: "Activity across every tracked project in the selected range.",
  },
  metrics: {
    activeToday: "Active Today",
    dailyGoal: "Daily Goal",
    topThreeFileShare: "Top-3 File Share",
    currentFlow: "Current Flow",
    characterEditVolume: "Character Edit Volume",
    approximateLineActivity: "Approx. Line Activity",
    currentDiagnostics: "Current Diagnostics",
    gitContext: "Git Context",
    projectTime: "Project Time",
    characterEditsPerHour: "Character Edits / Active Hour",
    removalShare: "Removal Share (Approx.)",
    errors: "Errors",
    warnings: "Warnings",
    saves: "Saves",
    debugTime: "Debug Time",
    trackedTime: "Tracked Time",
    projects: "Projects",
    mostActiveHour: "Most Active Hour",
    uniqueActiveFiles: "Unique Active Files",
    flowBlocks: "Flow Blocks",
  },
  panels: {
    todayTimeline: "Today · 15-Minute Activity",
    focusProfile: "Focus Profile",
    projectDistribution: "Project Distribution",
    languageDistribution: "Language Distribution",
    sessionLanguages: "Session Languages",
    activeFiles: "Active Files",
    activityTrend: "Activity Trend",
    languages: "Languages",
    mostActiveFiles: "Most Active Files",
    diagnosticsTrend: "Diagnostics Trend",
    branchMix: "Branch Mix",
    currentSignals: "Current Signals",
    weeklyHeatmap: "Weekly Heatmap",
    topProjects: "Top Projects",
    globalLanguages: "Global Languages",
  },
  empty: {
    noActivity: "No activity yet",
    noActiveFile: "No active file",
    noSessionLanguages: "No session languages yet",
    noActiveFilesToday: "No active files today",
    noLanguagesInRange: "No languages in this range",
    noActivityInRange: "No activity in this range",
    gitUnavailable: "Git unavailable",
    gitDisabled: "Git tracking is disabled",
    noRepository: "No Git repository for this project",
    noBranchActivity: "No branch activity in this range",
    diagnosticsUnavailable: "Diagnostics unavailable",
    noGlobalLanguageActivity: "No global language activity",
    overviewTitle: "No activity yet today",
    overviewBody:
      "DevTracker will show active time, focus context, and distributions here after your first tracked interaction.",
    noProjectDistribution: "No project activity yet",
    noLanguageDistribution: "No language activity yet",
  },
  dayNames: ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"],
  chartLabels: {
    hours: "Hours",
    errors: "Errors",
    warnings: "Warnings",
    info: "Info",
    activeMinutes: "Active minutes",
  },
  tableHeaders: {
    file: ["File", "Time", "Activity samples"],
    project: ["Project", "Time", "Top-3 share"],
  },
  signals: {
    errors: "Errors",
    warnings: "Warnings",
    info: "Info",
    hints: "Hints",
    dirtyFiles: "Dirty files",
  },
  phrases: {
    session: "Session",
    longest: "Longest",
    of: "of",
    editEvents: "edit events",
    largeEditEvents: "large edit events",
    inserted: "inserted",
    removedLineBreaksApprox: "removed line breaks (approx.)",
    errors: "errors",
    warnings: "warnings",
    trackedDays: "tracked days",
    observedEditorTransitions: "Observed editor transitions",
    approximateLineBreakChanges: "approximate line-break changes",
    tracked: "tracked",
    savesPerHour: "saves/hour",
  },
  initial: {
    zeroEditEvents: "0 edit events",
    approximateNetZeroLineBreaks: "Approx. net 0 line breaks",
    zeroWarnings: "0 warnings",
    zeroSavesPerHour: "0 saves/hour",
    zeroObservedEditorTransitions: "Observed editor transitions 0",
    legacyApproximation: "Legacy v1 approximation",
    zeroApproximateLineBreakChanges: "0 approximate line-break changes",
  },
  aria: {
    activeTimeToday: "Active time today",
    dailyGoalProgress: "Daily goal progress",
    topThreeFileShare: "Top three file share",
    currentFlowBlock: "Current flow block",
    characterEditVolume: "Character edit volume",
    approximateLineActivity: "Approximate line activity",
    currentDiagnostics: "Current diagnostics",
    gitContext: "Git context",
    activeHoursTodayChart:
      "Bar chart of active time in 15-minute buckets across today",
    projectHoursChart: "Bar chart of project active hours",
    diagnosticsChart: "Stacked chart of diagnostics by severity",
  },
  status: {
    dataUnavailable: "Dashboard data is temporarily unavailable",
    currentProject: "Current Project",
    currentSnapshot: "Current snapshot",
    selectedRange: "Selected range",
    allTrackedActivity: "All tracked activity",
    withActivity: "With activity",
    targetZeroMinutes: "Target 0m",
    sessionZeroMinutes: "Session 0m",
    longestZeroMinutes: "Longest 0m",
    selectProjectToContinue: "Select a project to view project-specific data.",
    loading: "Loading dashboard data…",
    trackedAcrossProjects: "Tracked across active projects today",
    goalNotConfigured: "Daily goal unavailable",
    fileDetailUnavailable: "File detail is disabled",
    exactRetainedFileCount: "Distinct retained file identities with activity",
    observedFlowBlocks: "Observed interaction-based flow blocks today",
    updatedJustNow: "Updated just now",
    tracking: {
      active: "Tracking",
      inactive: "Inactive",
      paused: "Paused",
      unfocused: "Unfocused",
    },
  },
  focusProfile: {
    topThreeFiles: "Top-3 file share",
    topThreeFilesDescription:
      "Share of active time in the three most active retained files.",
    fileSwitches: "File switches / active hour",
    fileSwitchesDescription:
      "Confirmed file changes normalized by tracked active time.",
    typicalFlow: "Typical flow block",
    typicalFlowDescription:
      "Average active time inside an observed interaction-based flow block.",
    unavailable: "Unavailable",
  },
} as const;

export type EnglishStrings = typeof ENGLISH_STRINGS;
